#!/usr/bin/env npx tsx
// scripts/generate-catalog.ts
// Build-time script: scans a yard directory of .mql files and generates
// a static TypeScript catalog at src/data/mxql-catalog.ts.
//
// Usage: npx tsx scripts/generate-catalog.ts <yard-path>

import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, relative, dirname, basename } from "node:path";
import { parseMqlFile } from "../src/yard/parser.js";
import type { CatalogEntry } from "../src/yard/types.js";

const YARD_PATH = process.argv[2];
if (!YARD_PATH) {
  console.error("Usage: npx tsx scripts/generate-catalog.ts <yard-path>");
  process.exit(1);
}

const OUTPUT_PATH = join(
  import.meta.dirname ?? dirname(new URL(import.meta.url).pathname),
  "..",
  "src",
  "data",
  "mxql-catalog.ts"
);

/** Strip {m5}, {h1}, etc. from category name */
function stripModifier(cat: string): string {
  return cat.replace(/\{[^}]+\}$/, "");
}

async function scanDir(dir: string, entries: string[]): Promise<void> {
  let items: string[];
  try {
    items = await readdir(dir);
  } catch {
    return;
  }
  for (const item of items) {
    const fullPath = join(dir, item);
    const s = await stat(fullPath).catch(() => null);
    if (!s) continue;
    if (s.isDirectory()) {
      await scanDir(fullPath, entries);
    } else if (item.endsWith(".mql")) {
      entries.push(fullPath);
    }
  }
}

async function main() {
  const files: string[] = [];
  await scanDir(YARD_PATH, files);
  files.sort();

  console.log(`Found ${files.length} .mql files in ${YARD_PATH}`);

  const catalogEntries: CatalogEntry[] = [];
  const rawMap: Record<string, string> = {};

  for (const file of files) {
    const content = await readFile(file, "utf-8");
    const relPath = relative(YARD_PATH, file).replace(/\\/g, "/").replace(/\.mql$/, "");
    const domain = dirname(relPath).replace(/\\/g, "/");
    const metadata = parseMqlFile(content);

    const baseCategories = [
      ...new Set(metadata.categories.map(stripModifier)),
    ];

    catalogEntries.push({
      path: relPath,
      domain: domain === "." ? basename(relPath) : domain,
      description: metadata.comments.join(" / "),
      categories: metadata.categories,
      baseCategories,
      parameters: metadata.parameters,
      headerTypes: metadata.headerTypes,
      selectFields: metadata.selectFields,
      joins: metadata.joins,
      loadType: metadata.loadType,
    });

    rawMap[relPath] = content;
  }

  // Generate TypeScript source
  const tsLines: string[] = [
    "// AUTO-GENERATED by scripts/generate-catalog.ts — DO NOT EDIT",
    `// Generated from ${files.length} .mql files`,
    "// Re-generate: npx tsx scripts/generate-catalog.ts <yard-path>",
    "",
    'import type { CatalogEntry } from "../yard/types.js";',
    "",
    `export const CATALOG_ENTRIES: CatalogEntry[] = ${JSON.stringify(catalogEntries, null, 2)};`,
    "",
    `export const CATALOG_RAW: Record<string, string> = ${JSON.stringify(rawMap, null, 2)};`,
    "",
  ];

  await writeFile(OUTPUT_PATH, tsLines.join("\n"), "utf-8");
  console.log(`Generated ${OUTPUT_PATH}`);
  console.log(`  ${catalogEntries.length} entries, ${Object.keys(rawMap).length} raw queries`);
}

main().catch((err) => {
  console.error("Failed to generate catalog:", err);
  process.exit(1);
});
