#!/usr/bin/env npx tsx
// scripts/generate-field-metadata.ts
// Build-time script: parses combined_metrics_v2.yaml and generates
// a static TypeScript field metadata file at src/data/field-metadata.ts.
//
// Usage: npx tsx scripts/generate-field-metadata.ts [yaml-path]
// Default: ~/git_hub/simple_opslake_mcp/src/simple_opslake_mcp/data/combined_metrics_v2.yaml

import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { parseAllDocuments } from "yaml";

const DEFAULT_YAML_PATH = join(
  process.env.HOME ?? "~",
  "git_hub/simple_opslake_mcp/src/simple_opslake_mcp/data/combined_metrics_v2.yaml"
);

const YAML_PATH = process.argv[2] ?? DEFAULT_YAML_PATH;

const OUTPUT_PATH = join(
  import.meta.dirname ?? dirname(new URL(import.meta.url).pathname),
  "..",
  "src",
  "data",
  "field-metadata.ts"
);

interface RawField {
  description?: string;
  summary_guide?: string;
  normal_operation?: {
    min?: number;
    max?: number;
    recommended?: string | number;
    related_fields?: string[];
  };
}

interface RawDocument {
  name: string;
  definition?: {
    category?: {
      category?: string;
      title?: string;
      description?: string;
      interval?: string;
      pk?: string[];
      supports?: { platform?: string[] };
    };
    tags?: Record<string, unknown>;
    fields?: Record<string, RawField>;
  };
}

async function main() {
  console.log(`Reading YAML from: ${YAML_PATH}`);
  const yamlContent = await readFile(YAML_PATH, "utf8");

  const docs = parseAllDocuments(yamlContent);
  console.log(`Parsed ${docs.length} YAML documents`);

  const categories: Record<string, unknown> = {};
  let totalFields = 0;

  for (const doc of docs) {
    const data = doc.toJSON() as RawDocument;
    if (!data?.name || !data?.definition) continue;

    const cat = data.definition.category ?? {};
    const fields = data.definition.fields ?? {};

    const fieldEntries: Record<string, unknown> = {};
    for (const [fieldName, fieldData] of Object.entries(fields)) {
      if (!fieldData?.summary_guide) continue; // skip fields without guidance

      const entry: Record<string, unknown> = {
        summary_guide: fieldData.summary_guide,
      };
      if (fieldData.description) {
        entry.description = fieldData.description;
      }
      if (fieldData.normal_operation) {
        const no: Record<string, unknown> = {};
        if (fieldData.normal_operation.min !== undefined)
          no.min = fieldData.normal_operation.min;
        if (fieldData.normal_operation.max !== undefined)
          no.max = fieldData.normal_operation.max;
        if (fieldData.normal_operation.recommended !== undefined)
          no.recommended = String(fieldData.normal_operation.recommended);
        if (
          fieldData.normal_operation.related_fields &&
          fieldData.normal_operation.related_fields.length > 0
        )
          no.related_fields = fieldData.normal_operation.related_fields;
        entry.normal_operation = no;
      }
      fieldEntries[fieldName] = entry;
      totalFields++;
    }

    if (Object.keys(fieldEntries).length === 0) continue;

    categories[data.name] = {
      title: cat.title ?? data.name,
      description: cat.description ?? "",
      interval: cat.interval ?? "",
      platforms: cat.supports?.platform ?? [],
      fields: fieldEntries,
    };
  }

  const categoryCount = Object.keys(categories).length;
  console.log(`Generated ${categoryCount} categories with ${totalFields} fields`);

  // Generate TypeScript output
  const tsContent = [
    "// AUTO-GENERATED by scripts/generate-field-metadata.ts — DO NOT EDIT",
    `// Generated from ${categoryCount} categories, ${totalFields} fields`,
    "// Re-generate: npm run generate-field-metadata [yaml-path]",
    "",
    "export interface NormalOperation {",
    "  min?: number;",
    "  max?: number;",
    "  recommended?: string;",
    "  related_fields?: string[];",
    "}",
    "",
    "export interface FieldMeta {",
    "  description?: string;",
    "  summary_guide: string;",
    "  normal_operation?: NormalOperation;",
    "}",
    "",
    "export interface CategoryMeta {",
    "  title: string;",
    "  description: string;",
    "  interval: string;",
    "  platforms: string[];",
    "  fields: Record<string, FieldMeta>;",
    "}",
    "",
    `export const FIELD_METADATA: Record<string, CategoryMeta> = ${JSON.stringify(categories, null, 2)};`,
    "",
  ].join("\n");

  await writeFile(OUTPUT_PATH, tsContent, "utf8");
  console.log(`Written to: ${OUTPUT_PATH} (${(tsContent.length / 1024).toFixed(0)}KB)`);
}

main().catch((err) => {
  console.error("Failed to generate field metadata:", err);
  process.exit(1);
});
