// src/data/field-metadata-en.ts
// HAND-MAINTAINED — not generated. English overrides for the handful of
// FIELD_METADATA entries whose upstream YAML description is still Korean.
//
// field-metadata.ts is regenerated by `npm run generate-field-metadata` from the
// upstream YAML, so fixing the strings there would be undone on the next run.
// These overrides are applied at lookup time in src/utils/field-guide.ts instead,
// and survive regeneration. When upstream translates a description, delete the
// matching entry here.

/** Category-level `description` overrides, keyed by category name. */
export const CATEGORY_DESCRIPTION_EN: Record<string, string> = {
  url_stat_all: "Status breakdown across all monitored URLs",
  server_pc_tcpv4: "Server monitoring — Windows netstat (TCP v4)",
  db_mysql_tables: "MySQL table information",
};

/** Field-level `description` overrides, keyed by category then field name. */
export const FIELD_DESCRIPTION_EN: Record<string, Record<string, string>> = {
  url_stat_all: {
    normal: "Number of URLs in a normal state",
    total: "Total number of URLs",
    error: "Number of URLs in an error state",
  },
  agent_status_summary: {
    isRebooted: "Whether the server was rebooted",
    inActTime: "Time at which the agent became inactive",
    startTime: "Time at which the agent started",
    oid: "oid value",
    isActive: "Whether the agent is active",
    lastActTime: "Last time the agent was seen active",
    isRestart: "Whether the agent was restarted",
    uptime: "Time at which the server started",
    status: "Agent status value",
  },
  db_cubrid_counter: {
    num_plan_cache_full:
      "Number of times victim search was attempted because the cache entry count exceeded the maximum",
  },
};
